version: 1
builder:
  configs:
    - documentation_targets:
        - SnapshotPreferences
        - Snapshotting
        - SnapshottingTests
    - platform: ios
      scheme: PreviewGallery
    - platform: macos
      scheme: PreviewGallery
