name: Pull Request Build

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-14
    strategy:
      matrix:
        xcode-version: [15.4, 16.1]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Xcode select ${{ matrix.xcode-version }}
        run: sudo xcode-select -s '/Applications/Xcode_${{ matrix.xcode-version }}.app/Contents/Developer'
      - name: Get Swift Version
        run: |
          SWIFT_MAJOR_VERSION=$(swift --version 2>&1 | awk '/Apple Swift version/ { split($7, ver, "."); print ver[1]; exit }')
          echo "Swift major version: $SWIFT_MAJOR_VERSION"
          echo "SWIFT_VERSION=$SWIFT_MAJOR_VERSION.0" >> "$GITHUB_ENV"
      - name: Build TestApp
        run: cd Examples && xcodebuild build -scheme DemoApp -sdk iphonesimulator -destination 'generic/platform=iOS Simulator' -project DemoApp/DemoApp.xcodeproj
      - name: Build Snapshotting
        run: xcodebuild build -scheme Snapshotting -sdk iphonesimulator -destination 'generic/platform=iOS Simulator'
      - name: Build SnapshottingTests
        run: xcodebuild build -scheme SnapshottingTests -sdk iphonesimulator -destination 'generic/platform=iOS Simulator'
  build-tvos:
      runs-on: macos-14
      strategy:
        matrix:
          xcode-version: [15.4, 16.1]

      steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Xcode select ${{ matrix.xcode-version }}
        run: sudo xcode-select -s '/Applications/Xcode_${{ matrix.xcode-version }}.app/Contents/Developer'
      - name: Get Swift Version
        run: |
          SWIFT_MAJOR_VERSION=$(swift --version 2>&1 | awk '/Apple Swift version/ { split($7, ver, "."); print ver[1]; exit }')
          echo "Swift major version: $SWIFT_MAJOR_VERSION"
          echo "SWIFT_VERSION=$SWIFT_MAJOR_VERSION.0" >> "$GITHUB_ENV"
      - name: Build PreviewGallery
        run: xcodebuild build -scheme PreviewGallery -sdk appletvsimulator -destination 'generic/platform=tvOS Simulator'
      - name: Build Snapshotting
        run: xcodebuild build -scheme Snapshotting -sdk appletvsimulator -destination 'generic/platform=tvOS Simulator'
      - name: Build SnapshottingTests
        run: xcodebuild build -scheme SnapshottingTests -sdk appletvsimulator -destination 'generic/platform=tvOS Simulator'
  build-visionos:
      runs-on: macos-15
      strategy:
        matrix:
          xcode-version: [15.4, 16.1]

      steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Xcode select ${{ matrix.xcode-version }}
        run: sudo xcode-select -s '/Applications/Xcode_${{ matrix.xcode-version }}.app/Contents/Developer'
      - name: Get Swift Version
        run: |
          SWIFT_MAJOR_VERSION=$(swift --version 2>&1 | awk '/Apple Swift version/ { split($7, ver, "."); print ver[1]; exit }')
          echo "Swift major version: $SWIFT_MAJOR_VERSION"
          echo "SWIFT_VERSION=$SWIFT_MAJOR_VERSION.0" >> "$GITHUB_ENV"
      - name: Build TestApp
        run: cd Examples && xcodebuild build -scheme DemoApp -sdk xrsimulator -destination 'generic/platform=visionOS Simulator' -project DemoApp/DemoApp.xcodeproj
      - name: Build Snapshotting
        run: xcodebuild build -scheme Snapshotting -sdk xrsimulator -destination 'generic/platform=visionOS Simulator'
      - name: Build SnapshottingTests
        run: xcodebuild build -scheme SnapshottingTests -sdk xrsimulator -destination 'generic/platform=visionOS Simulator'
  build-watchos:
      runs-on: macos-14
      strategy:
        matrix:
          xcode-version: [15.4, 16.1]

      steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Xcode select ${{ matrix.xcode-version }}
        run: sudo xcode-select -s '/Applications/Xcode_${{ matrix.xcode-version }}.app/Contents/Developer'
      - name: Get Swift Version
        run: |
          SWIFT_MAJOR_VERSION=$(swift --version 2>&1 | awk '/Apple Swift version/ { split($7, ver, "."); print ver[1]; exit }')
          echo "Swift major version: $SWIFT_MAJOR_VERSION"
          echo "SWIFT_VERSION=$SWIFT_MAJOR_VERSION.0" >> "$GITHUB_ENV"
      - name: Build Test Watch App
        run: cd Examples && xcodebuild build -scheme 'Demo Watch App' -sdk watchsimulator -destination 'generic/platform=watchOS Simulator' -project DemoApp/DemoApp.xcodeproj CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
      - name: Build Snapshotting
        run: xcodebuild build -scheme Snapshotting -sdk watchsimulator -destination 'generic/platform=watchOS Simulator'
      - name: Build SnapshottingTests
        run: xcodebuild build -scheme SnapshottingTests -sdk watchsimulator -destination 'generic/platform=watchOS Simulator'
  build-macos:
      runs-on: macos-14
      strategy:
        matrix:
          xcode-version: [15.4, 16.1]

      steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Xcode select ${{ matrix.xcode-version }}
        run: sudo xcode-select -s '/Applications/Xcode_${{ matrix.xcode-version }}.app/Contents/Developer'
      - name: Get Swift Version
        run: |
          SWIFT_MAJOR_VERSION=$(swift --version 2>&1 | awk '/Apple Swift version/ { split($7, ver, "."); print ver[1]; exit }')
          echo "Swift major version: $SWIFT_MAJOR_VERSION"
          echo "SWIFT_VERSION=$SWIFT_MAJOR_VERSION.0" >> "$GITHUB_ENV"
      - name: Build PreviewGallery
        run: xcodebuild build -scheme PreviewGallery -sdk macosx -destination 'generic/platform=macOS'
      - name: Build Snapshotting
        run: xcodebuild build -scheme Snapshotting -sdk macosx -destination 'generic/platform=macOS'
      - name: Build SnapshottingTests
        run: xcodebuild build -scheme SnapshottingTests -sdk macosx -destination 'generic/platform=macOS'
  build-macos-catalyst:
      runs-on: macos-14
      strategy:
        matrix:
          xcode-version: [15.4, 16.1]

      steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Xcode select ${{ matrix.xcode-version }}
        run: sudo xcode-select -s '/Applications/Xcode_${{ matrix.xcode-version }}.app/Contents/Developer'
      - name: Get Swift Version
        run: |
          SWIFT_MAJOR_VERSION=$(swift --version 2>&1 | awk '/Apple Swift version/ { split($7, ver, "."); print ver[1]; exit }')
          echo "Swift major version: $SWIFT_MAJOR_VERSION"
          echo "SWIFT_VERSION=$SWIFT_MAJOR_VERSION.0" >> "$GITHUB_ENV"
      - name: Build PreviewGallery
        run: xcodebuild build -scheme PreviewGallery -sdk macosx -destination 'platform=macOS,variant=Mac Catalyst'
      - name: Build Snapshotting
        run: xcodebuild build -scheme Snapshotting -sdk macosx -destination 'platform=macOS,variant=Mac Catalyst'
      - name: Build SnapshottingTests
        run: xcodebuild build -scheme SnapshottingTests -sdk macosx -destination 'platform=macOS,variant=Mac Catalyst'
